//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewsFlash.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NewsFlash.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _______ {
            get {
                object obj = ResourceManager.GetObject("_______", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewsFlash is a RSS Feedreader. It is free and open-source and licensed under GNU Public License 3.0..
        /// </summary>
        internal static string aboutDescription {
            get {
                return ResourceManager.GetString("aboutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.cnbc.com/id/19746125/device/rss/rss.xml.
        /// </summary>
        internal static string bus1Link {
            get {
                return ResourceManager.GetString("bus1Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CNBC.
        /// </summary>
        internal static string bus1Name {
            get {
                return ResourceManager.GetString("bus1Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://prod-qt-images.s3.amazonaws.com/production/bloombergquint/feed.xml.
        /// </summary>
        internal static string bus2Link {
            get {
                return ResourceManager.GetString("bus2Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bloomberg.
        /// </summary>
        internal static string bus2Name {
            get {
                return ResourceManager.GetString("bus2Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Default_Pic {
            get {
                object obj = ResourceManager.GetObject("Default_Pic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to send a code to given email. Please note that, due to no SMTP server, renowned email services like gmail, outlook will not work. Please use something like &quot;temp-mail.org&quot; or similar websites to use this feature..
        /// </summary>
        internal static string emailErrorMessage {
            get {
                return ResourceManager.GetString("emailErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://rssfeeds.webmd.com/rss/rss.aspx?RSSSource=RSS_PUBLIC.
        /// </summary>
        internal static string health1Link {
            get {
                return ResourceManager.GetString("health1Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebMD.
        /// </summary>
        internal static string health1Name {
            get {
                return ResourceManager.GetString("health1Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.nytimes.com/svc/collections/v1/publish/http://www.nytimes.com/section/health/rss.xml.
        /// </summary>
        internal static string health2Link {
            get {
                return ResourceManager.GetString("health2Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NYT - Health.
        /// </summary>
        internal static string health2Name {
            get {
                return ResourceManager.GetString("health2Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.realwire.com/rss/?id=488.
        /// </summary>
        internal static string lifestyle1Link {
            get {
                return ResourceManager.GetString("lifestyle1Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RealWire.
        /// </summary>
        internal static string lifestyle1Name {
            get {
                return ResourceManager.GetString("lifestyle1Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.gq.com/feed/style/rss.
        /// </summary>
        internal static string lifestyle2Link {
            get {
                return ResourceManager.GetString("lifestyle2Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GQ.
        /// </summary>
        internal static string lifestyle2Name {
            get {
                return ResourceManager.GetString("lifestyle2Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logo1 {
            get {
                object obj = ResourceManager.GetObject("logo1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logo2 {
            get {
                object obj = ResourceManager.GetObject("logo2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logo3 {
            get {
                object obj = ResourceManager.GetObject("logo3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logo4 {
            get {
                object obj = ResourceManager.GetObject("logo4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap newsflash_logo_dark_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("newsflash_logo_dark_removebg_preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap newsflash_logo_light_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("newsflash_logo_light_removebg_preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon share_this {
            get {
                object obj = ResourceManager.GetObject("share_this", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.espn.com/espn/rss/soccer/news.
        /// </summary>
        internal static string sports1Link {
            get {
                return ResourceManager.GetString("sports1Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESPN Soccer.
        /// </summary>
        internal static string sports1Name {
            get {
                return ResourceManager.GetString("sports1Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://crickettimes.com/feed/.
        /// </summary>
        internal static string sports2Link {
            get {
                return ResourceManager.GetString("sports2Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CricketTimes.
        /// </summary>
        internal static string sports2Name {
            get {
                return ResourceManager.GetString("sports2Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://feeds.bbci.co.uk/news/world/rss.xml.
        /// </summary>
        internal static string world1Link {
            get {
                return ResourceManager.GetString("world1Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BBC.
        /// </summary>
        internal static string world1Name {
            get {
                return ResourceManager.GetString("world1Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.aljazeera.com/xml/rss/all.xml.
        /// </summary>
        internal static string world2Link {
            get {
                return ResourceManager.GetString("world2Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Al Jazeera.
        /// </summary>
        internal static string world2Name {
            get {
                return ResourceManager.GetString("world2Name", resourceCulture);
            }
        }
    }
}
